deploymentName: message-deployment
serviceName: message
appLabel: message
appName: message

replicaCount: 1

image:
  repository: johndlr/message
  tag: v1

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enable: true
config_enabled: false
eureka_enabled: false
resourceeserver_enabled: false
otel_enabled: false
kafka_enabled: true