server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email
    stream:
      bindings:
        email-in-0:
          destination: send-communication
          group: ${spring.application.name}
        email-out-0:
          destination: communication-sent
      kafka:
        binder:
          brokers:
            - localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true