deploymentName: flight-deployment
serviceName: flight
appLabel: flight
appName: flight

replicaCount: 1

image:
  repository: johndlr/flight
  tag: v1

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

appname_enable: true
config_enabled: true
eureka_enabled: true
resourceeserver_enabled: false
otel_enabled: true
kafka_enabled: false