deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: johndlr/eurekaserver
  tag: v1

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

appname_enable: true
config_enabled: true
eureka_enabled: false
resourceeserver_enabled: false
otel_enabled: true
kafka_enabled: false