deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: johndlr/gatewayserver
  tag: v1

containerPort: 8072

service:
  type: LoadBalancer
  port: 8072
  targetPort: 8072

appname_enable: true
config_enabled: true
eureka_enabled: true
resourceeserver_enabled: true
otel_enabled: true
kafka_enabled: false